# Generated by Django 4.2.3 on 2023-07-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='experience_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
