# Generated by Django 4.2.3 on 2023-07-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_catogory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
