# Generated by Django 4.2.3 on 2023-07-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='users',
            new_name='user',
        ),
    ]
